[theme]
base = "dark"
primaryColor = "#ba0c2f"
backgroundColor = "#000e29"
secondaryBackgroundColor = "#00163d"
dataframeBorderColor = "#949caa"
borderColor = "#ba0c2f"

[server]
fileWatcherType = "none"